
import ENV from "./env";

import {
    deepCloneStyle,  
    deepCloneSection,  
    deepCloneArray,  
    filebrowserCallback,  
    getElementName,  
    getTemplateStyle,  
    getDraggedElement,  
    getChangeStyleOfElement,  
    getHoveredElement,  
    getColumnStrNumber,  
    getColumnStr,  
    convertHexToRGB,  
    convertRgbaToHex,  
    getClassFromSelector,  
    setClassesName,  
    generateClassNameStr,  
    generateFormClassNameStr,  
    generateMenuClassNameStr,  
    generateChildClassNameStr,  
    isObj,  
    getTypeOfElement,  
    getSeoUrlFromPageId  
} from "./functions";

import MainContent from "../components/pagepreview/components/MainContent";

import StyleGenerater from "../components/pagepreview/components/Atoms/StyleGenerater";
import FileManager from '../components/componentsettings/components/Atoms/FileManager';
import DefaultImage from "../components/pagepreview/components/Atoms/DefaultImage";
import PreviewElement from "../components/pagepreview/components/Atoms/PreviewElement";
import { ToastContainer, toast } from 'react-toastify';

import { 
    CloneCollectionData,
    getCollectionData,
    getSingleCollectionData,
    createCollectionData,
    deleteCollectionData,
    deleteCollectionDataImage,
    deleteCollectionDataImageMulti,
    deleteS3Image,
    updateCollectionData,
    publishCollectionData,
    UploadCollectionData,
} from "../service/pagepreview/CollectionDataService";

import { 
    GetAllCollection,
    ViewCollection,
    AddCollection,
    UpdateCollection,
    DeleteCollection,
    AddField,
    AddFieldAtDefault,
    DeleteField,
    UpdateField,
} from "../service/pagepreview/CollectionService";

import { 
    GetDirectories,
    CreateFolder,
    uploadImage,
} from "../service/pagepreview/Directories";

import { 
    GetAllElements,
    SaveSection,
    UpdateSectionApi,
    DeleteSectionApi,
    CloneSectionApi,
    GetAllTags,
    GetSectionDetail,
    GetSection,
    GetAllSectionTags,
} from "../service/pagepreview/ElementServices";

import { 
    deleteFile,
    renameFileService,
    exportMultipleDocs,
} from "../service/pagepreview/FolderServices";

import { 
    CalendarFetcher,
    addHolidayFetcher,
    addLeave,
    editHolidayFetcher,
    masterServiceFetch,
    masterService,
    AddFolder,
    uploadFileToFolder,
    FetchFolders,
    FolderDelete,
} from "../service/pagepreview/ModalServices";

import { 
    GetGoogleFonts,
    GetAllCollectionData,
    GetCollectionData,
    CreatePage,
    SubmitFormApi,
    GetSiteData,
    SwrGetSiteData,
    GetThemeSiteStyles,
    GetAutoResponderData,
    GetPages,
    GetPageVariants,
    DeletePage,
    ClonePage,
    UpdatePage,
    PageSortOrder,
    UpdateSiteApi,
} from "../service/pagepreview/PagesServices";

import { 
    CreateTemplate,
    DeleteTemplate,
    UpdateTemplate,
    CloneTemplate,
    UpdateSplitTesting,
    CopyTemplate,
    CopyToTemplate,
    GetTemplateDetail,
} from "../service/pagepreview/TemplateServices";

export {
    ENV,
    deepCloneStyle,  
    deepCloneSection,  
    deepCloneArray,  
    filebrowserCallback,  
    getElementName,  
    getTemplateStyle,  
    getDraggedElement,  
    getChangeStyleOfElement,  
    getHoveredElement,  
    getColumnStrNumber,  
    getColumnStr,  
    convertHexToRGB,  
    convertRgbaToHex,  
    getClassFromSelector,  
    setClassesName,  
    generateClassNameStr,  
    generateFormClassNameStr,  
    generateMenuClassNameStr,  
    generateChildClassNameStr,  
    isObj,  
    getTypeOfElement,  
    getSeoUrlFromPageId,
    MainContent,
    StyleGenerater,
    FileManager,
    DefaultImage,
    PreviewElement,
    ToastContainer, 
    toast,
    CloneCollectionData,
    getCollectionData,
    getSingleCollectionData,
    createCollectionData,
    deleteCollectionData,
    deleteCollectionDataImage,
    deleteCollectionDataImageMulti,
    deleteS3Image,
    updateCollectionData,
    publishCollectionData,
    UploadCollectionData,
    GetAllCollection,
    ViewCollection,
    AddCollection,
    UpdateCollection,
    DeleteCollection,
    AddField,
    AddFieldAtDefault,
    DeleteField,
    UpdateField,
    GetDirectories,
    CreateFolder,
    uploadImage,
    GetAllElements,
    SaveSection,
    UpdateSectionApi,
    DeleteSectionApi,
    CloneSectionApi,
    GetAllTags,
    GetSectionDetail,
    GetSection,
    GetAllSectionTags,
    deleteFile,
    renameFileService,
    exportMultipleDocs,
    CalendarFetcher,
    addHolidayFetcher,
    addLeave,
    editHolidayFetcher,
    masterServiceFetch,
    masterService,
    AddFolder,
    uploadFileToFolder,
    FetchFolders,
    FolderDelete,
    GetGoogleFonts,
    GetAllCollectionData,
    GetCollectionData,
    CreatePage,
    SubmitFormApi,
    GetSiteData,
    SwrGetSiteData,
    GetThemeSiteStyles,
    GetAutoResponderData,
    GetPages,
    GetPageVariants,
    DeletePage,
    ClonePage,
    UpdatePage,
    PageSortOrder,
    UpdateSiteApi,
    CreateTemplate,
    DeleteTemplate,
    UpdateTemplate,
    CloneTemplate,
    UpdateSplitTesting,
    CopyTemplate,
    CopyToTemplate,
    GetTemplateDetail,
}