export const ElementData = [
                                {
                                    "elementID":1,
                                    "elementName":"Grids"
                                },
                                {
                                    "elementID":2,
                                    "elementName":"Buttons"
                                },
                                {
                                    "elementID":3,
                                    "elementName":"Forms"
                                },
                                {
                                    "elementID":4,
                                    "elementName":"Timers"
                                },
                                {
                                    "elementID":5,
                                    "elementName":"Video"
                                },
                                {
                                    "elementID":6,
                                    "elementName":"Image"
                                },
                                {
                                    "elementID":7,
                                    "elementName":"Progress Bar"
                                },
                                {
                                    "elementID":8,
                                    "elementName":"Social Icons"
                                },
                                {
                                    "elementID":9,
                                    "elementName":"Menu"
                                },
                                {
                                    "elementID":10,
                                    "elementName":"Text"
                                },
                                {
                                    "elementID":11,
                                    "elementName":"Seperators"
                                },
                                {
                                    "elementID":9,
                                    "elementName":"HTML"
                                },
                                {
                                    "elementID":12,
                                    "elementName":"Collections"
                                },
                                {
                                    "elementID":13,
                                    "elementName":"Banner"
                                },
                            ];